 opkg update
 opkg install --force-depends ca-certificates
 opkg install --force-depends git
 opkg install --force-depends git-http
 opkg install --force-depends libbz2
 opkg install --force-depends libcurl
 opkg install --force-depends libdb47
 opkg install --force-depends libffi
 opkg install --force-depends libgcc
 opkg install --force-depends libgdbm
 opkg install --force-depends libgmp
 opkg install --force-depends liblua
 opkg install --force-depends libncurses
 opkg install --force-depends libncursesw
 opkg install --force-depends libopenssl
 opkg install --force-depends libpcre
 opkg install --force-depends libpolarssl
 opkg install --force-depends libpthread
 opkg install --force-depends libreadline
 opkg install --force-depends librt
 opkg install --force-depends libruby
 opkg install --force-depends libubox
 opkg install --force-depends libubus
 opkg install --force-depends libubus-lua
 opkg install --force-depends libxml2
 opkg install --force-depends libyaml
 opkg install --force-depends python
 opkg install --force-depends python-base
 opkg install --force-depends python-codecs
 opkg install --force-depends python-compiler
 opkg install --force-depends python-ctypes
 opkg install --force-depends python-db
 opkg install --force-depends python-light
 opkg install --force-depends ruby
 opkg install --force-depends ruby-bigdecimal
 opkg install --force-depends ruby-cgi
 opkg install --force-depends ruby-csv
 opkg install --force-depends ruby-datetime
 opkg install --force-depends ruby-dbm
 opkg install --force-depends ruby-debuglib
 opkg install --force-depends ruby-digest
 opkg install --force-depends ruby-drb
 opkg install --force-depends ruby-enc
 opkg install --force-depends ruby-enc-extra
 opkg install --force-depends ruby-erb
 opkg install --force-depends ruby-fiddle
 opkg install --force-depends ruby-filelib
 opkg install --force-depends ruby-gdbm
 opkg install --force-depends ruby-gems
 opkg install --force-depends ruby-io-console
 opkg install --force-depends ruby-irb
 opkg install --force-depends ruby-json
 opkg install --force-depends ruby-logger
 opkg install --force-depends ruby-math
 opkg install --force-depends ruby-minitest
 opkg install --force-depends ruby-misc
 opkg install --force-depends ruby-mkmf
 opkg install --force-depends ruby-multithread
 opkg install --force-depends ruby-net
 opkg install --force-depends ruby-nkf
 opkg install --force-depends ruby-openssl
 opkg install --force-depends ruby-optparse
 opkg install --force-depends ruby-patterns
 opkg install --force-depends ruby-powerassert
 opkg install --force-depends ruby-prettyprint
 opkg install --force-depends ruby-pstore
 opkg install --force-depends ruby-psych
 opkg install --force-depends ruby-racc
 opkg install --force-depends ruby-rake
 opkg install --force-depends ruby-rbconfig
 opkg install --force-depends ruby-rdoc
 opkg install --force-depends ruby-readline
 opkg install --force-depends ruby-rexml
 opkg install --force-depends ruby-rinda
 opkg install --force-depends ruby-ripper
 opkg install --force-depends ruby-rss
 opkg install --force-depends ruby-sdbm
 opkg install --force-depends ruby-shell
 opkg install --force-depends ruby-socket
 opkg install --force-depends ruby-stdlib
 opkg install --force-depends ruby-testunit
 opkg install --force-depends ruby-unicodenormalize
 opkg install --force-depends ruby-uri
 opkg install --force-depends ruby-webrick
 opkg install --force-depends ruby-xmlrpc
 opkg install --force-depends ruby-yaml
 opkg install --force-depends ruby-zlib
 opkg install --force-depends terminfo
 opkg install --force-depends vim-full
 opkg install --force-depends vim-runtime
 opkg install --force-depends zlib
 opkg install --force-depends zsh
