#!/bin/sh /etc/rc.common

START=70
USE_PROCD=1

_exec_verbose() {
  echo $1
  $($1)
}

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/didiagent
  procd_set_param respawn 3600 5 0
  procd_set_param stdout 0
  procd_set_param stderr 1
  procd_close_instance
}
