#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1
DEBUG=1

LOG_FILE="/tmp/log/miio.log.pipe"

LOG_TITLE=$0
mico_log() {
    logger -t $LOG_TITLE[$$] -p 3 "$*"
}

start_service() {
    procd_open_instance
    if [ $DEBUG = "1" ]; then
	procd_set_param command /usr/bin/miio_client -L $LOG_FILE -l 3
    else
	procd_set_param command /usr/bin/miio_client -L /dev/null
    fi
    procd_set_param respawn 3600 5 0
    procd_close_instance

    procd_open_instance
    procd_set_param command /usr/bin/miio_client_helper
    procd_set_param respawn 3600 5 0
    procd_close_instance

    sleep 2

    procd_open_instance
    procd_set_param command /usr/bin/miio_service
    procd_set_param respawn 3600 5 0
    procd_close_instance
}


